# Generated by Django 5.2.8 on 2025-11-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='src',
            field=models.TextField(),
        ),
    ]
