# Generated by Django 4.2.7 on 2025-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('facilities', 'Facilities'), ('startups', 'Startups'), ('events_alt', 'Events Alt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('application', 'Incubation Application'), ('user_registration', 'User Registration'), ('blog', 'Blog Update'), ('event', 'Event Update'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
