# Generated by Django 4.2.7 on 2025-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_program_event_alter_mediaitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
