# Generated by Django 5.2.8 on 2025-11-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_logo_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=255)),
                ('founded', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('current', 'Current Startup'), ('graduated', 'Graduated Startup')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('bio', models.TextField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo', to='api.startup')),
            ],
        ),
    ]
