# Generated by Django 4.2.7 on 2025-12-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
