# Generated by Django 5.2.8 on 2025-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_startup_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(max_length=500),
        ),
    ]
