# Generated by Django 4.2.7 on 2025-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
