# Generated by Django 5.2.8 on 2025-11-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_startup_facebook_startup_linkedin_startup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceos', to='api.startup'),
        ),
    ]
