# Generated by Django 5.2.8 on 2025-11-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_boardmember_founder_tbiceo_alter_startup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='linkedin',
        ),
    ]
