# Generated by Django 4.2.7 on 2025-12-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_formfield_formtemplate_formsubmission_formfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='experience_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentor',
            name='interested_in',
            field=models.CharField(choices=[('student_startups', 'Student Startups'), ('current_startups', 'Current Startups'), ('both', 'Both')], default='both', max_length=50),
        ),
        migrations.AddField(
            model_name='mentor',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Other', 'Other')], default='Mr', max_length=10),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
