# Generated by Django 5.2.8 on 2025-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_founder_email_remove_founder_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('SHARED', 'Shared Infrastructure'), ('TCETBI', 'TCETBI Infrastructure')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=50)),
                ('thumbnail', models.TextField()),
            ],
        ),
    ]
