# Generated by Django 4.2.7 on 2025-12-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mentor_created_at_mentor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
