# Generated by Django 5.2.8 on 2025-11-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_facility_facilityvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityvideo',
            name='video_id',
        ),
        migrations.AddField(
            model_name='facilityvideo',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
