# Generated by Django 5.2.8 on 2025-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_facilityvideo_video_id_facilityvideo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('upcoming', 'Upcoming')], max_length=20)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
                ('participants', models.IntegerField()),
                ('status', models.CharField(max_length=80)),
            ],
        ),
    ]
