# Generated by Django 4.2.7 on 2025-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_mentor_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(choices=[('funding_support', 'Funding Support'), ('mentoring_support', 'Mentoring Support'), ('idea_validation', 'Idea Validation'), ('incubation_application', 'Incubation Application'), ('mentor_application', 'Mentor Application'), ('contact', 'Contact Form')], max_length=50, unique=True),
        ),
    ]
