# Generated by Django 5.2.8 on 2025-11-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
        migrations.RemoveField(
            model_name='program',
            name='participants',
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('ended', 'Ended')], max_length=20),
        ),
    ]
