# Generated by Django 4.2.7 on 2026-03-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='owner_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='owner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='owner_linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
