# Generated by Django 5.2.8 on 2025-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_program_category_remove_program_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='startDate',
            field=models.DateField(),
        ),
    ]
