# Generated by Django 4.2.7 on 2026-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_startup_owner_company_name_startup_owner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
