# Generated by Django 5.2.8 on 2025-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_program_enddate_alter_program_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField()),
                ('album', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('events', 'Events'), ('facilities', 'Facilities'), ('startups', 'Startups'), ('programs', 'Programs')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
