# Generated by Django 4.2.7 on 2026-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_formsubmission_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_main_title',
            field=models.BooleanField(default=False),
        ),
    ]
