# Generated by Django 5.2.8 on 2025-11-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
