# Generated by Django 5.2.8 on 2026-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_formfield_is_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable/disable all outgoing email notifications')),
                ('google_sso_enabled', models.BooleanField(default=False, help_text='Enable/disable Google SSO login')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('application', 'Incubation Application'), ('user_registration', 'User Registration'), ('blog', 'Blog Update'), ('event', 'Event Update'), ('support', 'Support Request'), ('mentor', 'Mentor Application'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
