# Generated by Django 5.2.8 on 2026-06-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sitesettings_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='pitch_deck',
            field=models.TextField(blank=True, null=True),
        ),
    ]
