# Generated by Django 5.2.8 on 2025-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_blog_content_remove_blog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBIContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.TextField()),
                ('quick_title', models.CharField(default='Quick Contact', max_length=200)),
                ('quick_subtitle', models.CharField(default='Reach out to us for immediate assistance', max_length=255)),
                ('office_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('map_embed_url', models.TextField()),
            ],
        ),
    ]
