# Generated by Django 5.2.8 on 2025-11-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
