# Generated by Django 5.2.8 on 2025-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notification_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('resume_pdf', models.URLField(blank=True, null=True)),
                ('businessName', models.CharField(max_length=255)),
                ('salutation', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resMobile', models.CharField(max_length=20)),
                ('offMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('businessType', models.CharField(max_length=100)),
                ('legalEntity', models.CharField(max_length=100)),
                ('businessDescription', models.TextField()),
                ('services', models.JSONField(default=dict)),
                ('numChairs', models.IntegerField(blank=True, null=True)),
                ('fullTimeEmployees', models.IntegerField(blank=True, null=True)),
                ('partTimeEmployees', models.IntegerField(blank=True, null=True)),
                ('consultants', models.IntegerField(blank=True, null=True)),
                ('reference1', models.JSONField(default=dict)),
                ('reference2', models.JSONField(default=dict)),
                ('declaration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
