# Generated by Django 5.2.8 on 2025-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_incubationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubationapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
