# Generated by Django 5.2.8 on 2025-11-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_notification_type_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(max_length=255)),
                ('founded', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('products', models.JSONField(default=list)),
                ('ceo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_image', models.URLField(blank=True, max_length=500, null=True)),
                ('ceo_bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
