# Generated by Django 5.2.8 on 2025-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usercompanyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='ceo_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
