# Generated by Django 5.2.8 on 2025-11-30 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_usercompanyrequest_ceo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
