# Generated by Django 4.2.7 on 2025-12-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_mentor_validationrequest_mentoringrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
